name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t stay-booker-pro
      - name: Run tests
        run: |
          docker run stay-booker-pro npm test

      - name: Deploy to Hosting Service
        run: |
          # Add deployment commands here
